### ISSUE TITLE
XPRA method seems broken with the "No such file or directory" error

### ISSUE THREAD

**Issue by bencawkwell** [bencawkwell/dockerfile-dwarffortress#3]
This may be because of change on the system I use to connect, but when I just tested the XPRA method, after entering the "changeme" password I get the following error:

```
xpra initialization error: connection failed: [Errno 2] No such file or directory
```

**Comment by bencawkwell** [comment]
I still have issues using xpra, but now I find this in the xpra supervisor log in the container when trying to connect:

```
2017-02-01 21:58:30,757 New unix-domain connection received on /home/df/.xpra/47188b12fe91-100
2017-02-01 21:58:30,758 New unix-domain connection received on /home/df/.xpra/47188b12fe91-100
2017-02-01 21:58:30,763 Handshake complete; enabling connection
2017-02-01 21:58:30,765 server error processing new connection from Protocol(unix-domain socket:/home/df/.xpra/47188b12fe91-100): No module named dbus
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/xpra/server/server_core.py", line 893, in _process_hello
    self.hello_oked(proto, packet, c, auth_caps)
  File "/usr/lib/python2.7/dist-packages/xpra/server/server_base.py", line 1115, in hello_oked
    self.default_speed, self.default_min_speed)
  File "/usr/lib/python2.7/dist-packages/xpra/server/source.py", line 357, in __init__
    self.dbus_server = dbus_exception_wrap(make_dbus_server, "setting up client dbus instance")
  File "/usr/lib/python2.7/dist-packages/xpra/server/dbus/dbus_common.py", line 12, in dbus_exception_wrap
    v = fn()
  File "/usr/lib/python2.7/dist-packages/xpra/server/source.py", line 355, in make_dbus_server
    from xpra.server.dbus.dbus_source import DBUS_Source
  File "/usr/lib/python2.7/dist-packages/xpra/server/dbus/dbus_source.py", line 7, in <module>
    from xpra.dbus.helper import dbus_to_native
  File "/usr/lib/python2.7/dist-packages/xpra/dbus/helper.py", line 7, in <module>
    import dbus
ImportError: No module named dbus
2017-02-01 21:58:30,766 Disconnecting client /home/df/.xpra/47188b12fe91-100:
2017-02-01 21:58:30,766  server error (error accepting new connection)
```

That and the wrong display port is documented in the README, since I changed it some time ago in the ansible-dwarffortress project from 1 to 100!

**Comment by bencawkwell** [comment]
Seems all that is needed to fix this is to install python-dbus manually and it works, at least testing xpra version v1.0.2-r14944. Will need to add this to the ansible-dwarffortress project, and then bump the version used in the Dockerfile.
